"""End-to-end integration test for the pre-IPO / S-1 user journey.

Covers the demo flow without network access:

  1. universe.toml with a name-only pre-IPO filer loads without errors.
  2. form_counts emits the registration sentinel, not periodic forms.
  3. Planner expands the sentinel across the registration family and
     produces plan items for every form actually available.
  4. A built pack (simulated via fixtures) exposes S-1 metrics via the
     extract_s1_metrics_from_pack aggregator.
  5. The registration timeline renders a consecutive-pair redline with
     ranked changed sections.

If any step regresses, this single test catches it before merge.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from datetime import date
from pathlib import Path
from unittest.mock import patch

import pytest

from edgarpack.harvest.planner import plan_harvest
from edgarpack.harvest.registry import PackRegistry
from edgarpack.harvest.universe import CompanySpec, UniverseConfig
from edgarpack.query.kpi_discover import extract_s1_metrics_from_pack
from edgarpack.sec.submissions import (
    REGISTRATION_SENTINEL,
    FilingMeta,
    is_registration_form,
)

_S1_BODY = """\
# Prospectus Summary

We are a developer of wafer-scale AI compute systems. We estimate the total
addressable market at $150 billion, growing at 34% CAGR.

# Risk Factors

A significant portion of our revenue was generated by a single customer.

# Use of Proceeds

We intend to use the net proceeds approximately $150.0 million for research
and development, $80.0 million for manufacturing capacity expansion.

# Dilution

You will experience immediate dilution of $12.50 per share.

# Principal Stockholders

Name                        Shares           Percent
Acme Capital LP             12,500,000       18.4%
Founder Jane Doe             9,000,000       13.2%

# Underwriting

The lock-up period will be 180 days from the date of this prospectus.
"""


_S1A_BODY = """\
# Prospectus Summary

We are a developer of wafer-scale AI compute systems. We estimate the total
addressable market at $180 billion, growing at 34% CAGR.

# Risk Factors

A significant portion of our revenue was generated by a single customer and
that customer has the option to reduce orders materially.

# Use of Proceeds

We intend to use the net proceeds approximately $150.0 million for research
and development, $80.0 million for manufacturing capacity expansion, and
$40.0 million for working capital.

# Dilution

You will experience immediate dilution of $13.20 per share.

# Principal Stockholders

Name                        Shares           Percent
Acme Capital LP             12,500,000       17.1%
Founder Jane Doe             9,000,000       12.3%
Strategic Ventures Fund      5,250,000        7.2%

# Underwriting

The lock-up period will be 180 days from the date of this prospectus.
"""


def _build_pack(
    root: Path,
    accession: str,
    form_type: str,
    filing_date: str,
    cik: str,
    body: str,
    sections: list[tuple[str, str, str]],
) -> Path:
    """Create a pack directory with manifest.json, filing.full.md, and sections."""
    pack = root / accession
    pack.mkdir(parents=True, exist_ok=True)
    (pack / "sections").mkdir(exist_ok=True)

    manifest_sections: list[dict] = []
    for sid, rel_path, title in sections:
        # Extract the section's body from the full markdown by title match.
        chunks = body.split("# ")
        text = ""
        for chunk in chunks[1:]:
            if chunk.startswith(title):
                text = chunk[len(title) :].strip()
                break
        (pack / rel_path).write_text(text, encoding="utf-8")
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        manifest_sections.append({"id": sid, "path": rel_path, "title": title, "sha256": sha})

    (pack / "filing.full.md").write_text(body, encoding="utf-8")
    (pack / "manifest.json").write_text(
        json.dumps(
            {
                "schema_version": 1,
                "filing": {
                    "accession": accession,
                    "form_type": form_type,
                    "filing_date": filing_date,
                    "cik": cik,
                    "company_name": "Cerebras Systems Inc",
                },
                "sections": manifest_sections,
                "parser_version": "test",
            }
        )
    )
    return pack


def _filing(accession: str, form: str, filing_date: str, cik: str) -> FilingMeta:
    return FilingMeta(
        cik=cik,
        accession=accession,
        form_type=form,
        filing_date=date.fromisoformat(filing_date),
        primary_document="main.htm",
        company_name="Cerebras Systems Inc",
    )


@pytest.mark.asyncio
async def test_pre_ipo_journey_end_to_end(tmp_path):
    cik = "0002021728"
    packs_root = tmp_path / "packs" / cik

    # --- Step 1: universe entry with only name + forms_s1 validates ---------
    spec = CompanySpec(name="Cerebras Systems", forms_s1=4)
    assert spec.ticker is None and spec.cik is None
    assert spec.display_label == "Cerebras Systems"

    cfg = UniverseConfig(companies=[spec])

    # --- Step 2: form_counts emits registration sentinel only ---------------
    counts = cfg.form_counts(spec)
    assert counts == {REGISTRATION_SENTINEL: 4}

    # --- Step 3: planner expands sentinel, uses resolve_filer ---------------
    canned: dict[str, list[FilingMeta]] = {
        "S-1": [_filing("S1-001", "S-1", "2025-09-30", cik)],
        "S-1/A": [_filing("S1A-002", "S-1/A", "2025-10-15", cik)],
    }

    async def fake_list_filings(cik_arg, form_type=None, limit=10, force=False):
        return canned.get(form_type, [])

    async def fake_resolve(spec_arg):
        return cik, "Cerebras Systems Inc"

    registry = PackRegistry(tmp_path / "registry.db")
    try:
        with patch("edgarpack.harvest.planner.list_filings", new=fake_list_filings):
            with patch("edgarpack.harvest.planner.resolve_filer", new=fake_resolve):
                plan = await plan_harvest(cfg, registry)
    finally:
        registry.close()

    plan_accessions = {item.accession for item in plan.items}
    assert plan_accessions == {"S1-001", "S1A-002"}
    for item in plan.items:
        assert is_registration_form(item.form_type)
    # Plan errors list should be empty: no periodic forms were attempted.
    assert plan.errors == []

    # --- Step 4: built packs expose S-1 metrics through the aggregator ------
    _build_pack(
        packs_root,
        "S1-001",
        "S-1",
        "2025-09-30",
        cik,
        _S1_BODY,
        [
            ("s1_summary", "sections/summary.md", "Prospectus Summary"),
            ("s1_risk", "sections/risk.md", "Risk Factors"),
            ("s1_use", "sections/use.md", "Use of Proceeds"),
            ("s1_dilution", "sections/dilution.md", "Dilution"),
            ("s1_holders", "sections/holders.md", "Principal Stockholders"),
            ("s1_under", "sections/under.md", "Underwriting"),
        ],
    )
    s1a_pack = _build_pack(
        packs_root,
        "S1A-002",
        "S-1/A",
        "2025-10-15",
        cik,
        _S1A_BODY,
        [
            ("s1_summary", "sections/summary.md", "Prospectus Summary"),
            ("s1_risk", "sections/risk.md", "Risk Factors"),
            ("s1_use", "sections/use.md", "Use of Proceeds"),
            ("s1_dilution", "sections/dilution.md", "Dilution"),
            ("s1_holders", "sections/holders.md", "Principal Stockholders"),
            ("s1_under", "sections/under.md", "Underwriting"),
        ],
    )

    bundle = extract_s1_metrics_from_pack(s1a_pack)
    assert bundle is not None
    assert bundle.form_type == "S-1/A"
    # Every extractor should yield at least one hit against the S-1/A body.
    assert bundle.framing, "expected TAM / CAGR claims"
    assert bundle.use_of_proceeds, "expected use-of-proceeds items"
    assert bundle.dilution, "expected dilution claim"
    assert bundle.lockup, "expected lockup terms"
    assert bundle.principal_holders, "expected principal holders"

    # --- Step 5: CLI renders redline timeline against the fixture packs -----
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "edgarpack.cli",
            "timeline",
            "--series",
            "registration",
            "--cik",
            cik,
            "--packs",
            str(tmp_path / "packs"),
        ],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    out = result.stdout

    # Timeline header.
    assert "Registration timeline for CIK" in out
    # S-1 disclosures block surfaces framing + at least one other extractor.
    assert "S-1 disclosures in latest filing" in out
    assert "framing claims" in out
    # Redline pair.
    assert "S1-001" in out and "S1A-002" in out
    # At least one section changed; intensity and per-section markers rendered.
    assert "intensity" in out.lower()
    # Prospectus Summary changed ($150B -> $180B TAM): must appear.
    assert "Prospectus Summary" in out or "Risk Factors" in out
